export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SAVE_ENTREPRISE = "SAVE_ENTREPRISE";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const SAVE_EMPLOYE = "SAVE_EMPLOYE";
export const GET_INFORMATION = "GET_INFORMATION";
export const LIST_EMPLOYE = "LIST_EMPLOYE";
export const LIST_PROJECT = "LIST_PROJECT";
export const DELETE_EMPLOYE = "DELETE_EMPLOYE";
export const GET_EMPLOYE_INFORMATION = "GET_EMPLOYE_INFORMATION";
export const CREATE_PROJECT = "CREATE_PROJECT";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";